name: "build-test-pubtodockerhub"

# IMPORTANT : personnalisez cette variable pour que les images
# de votre application soient pousées sur dockerhub
# dans le repository ayant ce nom
# exemple, si vous indiquez : abesesr/abes-hello
#   alors l'image sera poussée sur https://hub.docker.com/r/abesesr/abes-hello
env:
  DOCKERHUB_IMAGE_PREFIX: abesesr/licencesnationales
  
on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
    branches:    
      - 'main'
      - 'develop'
    tags:        
      - '*'
  workflow_dispatch:

jobs:
  build-test-pubtodockerhub:
    runs-on: ubuntu-latest
    steps:

      - name: "Build: checkout source code"
        uses: actions/checkout@v3
        
      - name: "Build: build docker image"
        run: |
          docker build --build-arg HASH=$GITHUB_SHA . -t localimage:latest

      - name: "Push: prepare version from git tags/branchs"
        id: docker_tag_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE_PREFIX }}

      - name: "Push: login to DockerHub"
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin  
          
      - name: "Push: push docker image"
        run: |
          DOCKER_TAGS="${{ steps.docker_tag_meta.outputs.tags }}"
          for DOCKER_TAG in $DOCKER_TAGS
          do
            docker build . --target front-image -t ${DOCKER_TAG}-front
            docker push ${DOCKER_TAG}-front
          done
